### ISSUE TITLE
Could it  be docker for maze?tks

### ISSUE THREAD

**Issue by justincnn** [hsfzxjy/Harfbuzz-WASM-Fantasy#1]

**Comment by hsfzxjy** [comment]
It would be challenging to achieve this.

The maze game requires two things: 1) A `gedit` application patched with wasm-enabled libharfbuzz, and 2) a font file packed with wasm shaper lying at a system location. 

I don't know whether running GUI application from within docker is feasible, but anyway, good suggestion and I will try it!

**Comment by hsfzxjy** [comment]
This repo currently supports running with Docker image! Please refer to the latest README for more details.

Happy coding!
